"""Stable public imports for upright contracts; implementations have explicit owners."""

from __future__ import annotations

import math

from dataclasses import dataclass

from enum import StrEnum

from fractions import Fraction

from itertools import pairwise

from typing import Annotated, ClassVar, Literal, Self, TypeAlias, TypeVar

from pydantic import Field, StrictBool, StrictInt, model_validator

from spatialcf.domain.base import (
    CanonicalId,
    CanonicalModel,
    FactAvailabilityV2,
    FactCompletenessV2,
    FactSetV2,
    FiniteFloat,
    Quaternion,
    RigidTransformV2,
    Sha256Digest,
    Vec2,
    Vec3,
)

from spatialcf.domain.compatibility import PlanarTranslateCompilation

from spatialcf.domain.counterfactual import (
    CounterfactualProblemIR,
    CounterfactualSolveRequest,
    EditProgram,
    ExtensionFact,
    ExtensionFactBundle,
    SceneStateEnvelope,
)

from spatialcf.domain.definitions import (
    BooleanValue,
    CanonicalDefinitionEnvelope,
    CanonicalIdValue,
    CapabilityRef,
    DefinitionBundle,
    DefinitionRef,
    DigestValue,
    EnumSymbolValue,
    FiniteOrderedTupleValue,
    FiniteRealValue,
    HashBoundCanonicalModel,
    IntegerValue,
    IntervalValue,
    NamedTypedValue,
    RecordValue,
    ReferenceValue,
    TypedValue,
    ValueKind,
)

from spatialcf.domain.geometry import (
    CollisionBodyFactV2,
    GeometryInstanceV2,
    GeometryRoleV2,
)

from spatialcf.domain.operators import (
    OperationArgument,
    OperationInvocation,
    StateDeltaManifest,
    StateVariableRef,
)

from spatialcf.domain.outcomes import ResourceUsage

from spatialcf.domain.predicates import (
    AfterGoal,
    BeforePrecondition,
    GroundedObligation,
    GroundedObligationSet,
    ObservationObligation,
    PredicateAtom,
    PreservationInvariant,
)

from spatialcf.domain.profiles import (
    ActionSpaceProfile,
    ObjectiveExpression,
    ObjectiveTerm,
    OwnerRef,
    ProofPolicy,
    ResourcePolicy,
    SemanticsProfile,
)

from spatialcf.domain.scene import (
    BaselineObservation,
    CanonicalScene,
    ObjectPose,
    SupportSurfaceFact,
)

from spatialcf.domain.serialization import canonical_json_bytes, canonical_sha256

from spatialcf.domain._upright_se2.cells import (
    UprightSE2BackendAvailability,
    UprightSE2CompiledCell,
    _lifted_cell_order_key,
    UprightSE2CoverageArtifact,
    UprightSE2ProofLeafDisposition,
    UprightSE2RetainedOwnerOutcomeKind,
    UprightSE2CardinalProofTuple,
    UprightSE2ContinuousProofTuple,
)

from spatialcf.domain._upright_se2.compilation import (
    UprightSE2Compilation,
    UprightSE2ContinuousCompilation,
    _bound_state_leaf,
    _bound_translation_domain,
    _bound_cardinal_after_yaw,
    _bound_rotate_cardinal_xy,
    _bound_cardinal_quaternion,
    _bound_cardinal_compiled_cell,
    _validate_compilation_source_binding,
    _validate_continuous_compilation_source_binding,
)

from spatialcf.domain._upright_se2.constants import (
    UPRIGHT_SE2_PROFILE_REF,
    UPRIGHT_SE2_SEMANTICS_PROFILE_REF,
    UPRIGHT_SE2_YAW_TO_POSE_RULE_REF,
    UPRIGHT_SE2_DERIVED_SOURCE_HASH_DOMAIN,
    UPRIGHT_SE2_PROOF_MATERIAL_DEFINITION_REF,
    UPRIGHT_SE2_PROOF_MATERIAL_PAYLOAD_SCHEMA_REF,
    UPRIGHT_SE2_PROOF_MATERIAL_DISCRIMINATOR,
    UPRIGHT_SE2_CONTINUOUS_PROOF_MATERIAL_DEFINITION_REF,
    UPRIGHT_SE2_CONTINUOUS_PROOF_MATERIAL_PAYLOAD_SCHEMA_REF,
    UPRIGHT_SE2_CONTINUOUS_PROOF_MATERIAL_DISCRIMINATOR,
    UPRIGHT_SE2_SOLVE_POLICY_DEFINITION_REF,
    UPRIGHT_SE2_SOLVE_POLICY_PAYLOAD_SCHEMA_REF,
    UPRIGHT_SE2_EXACT_GLOBAL_CLAIM_DEFINITION_REF,
    UPRIGHT_SE2_FINITE_GAP_CLAIM_DEFINITION_REF,
    _UPRIGHT_SE2_PIVOT_STATE_HASH_DOMAIN,
    _UPRIGHT_SE2_UNCHANGED_LEAVES_HASH_DOMAIN,
    _UPRIGHT_SE2_YAW_TO_POSE_MAX_ULPS,
    _UPRIGHT_SE2_COMPILER_INPUT_FAMILY_REF,
    _UPRIGHT_SE2_COMPILER_INPUT_SCHEMA_REF,
    _UPRIGHT_SE2_COMPILER_INPUT_FACT_KEY,
    _UPRIGHT_SE2_STATE_FAMILY_REF,
    _UPRIGHT_SE2_STATE_SCHEMA_REF,
    _UPRIGHT_SE2_REAL_SCHEMA_REF,
    _UPRIGHT_SE2_INTEGER_SCHEMA_REF,
    _UPRIGHT_SE2_ID_SCHEMA_REF,
    _UPRIGHT_SE2_DIGEST_SCHEMA_REF,
    _UPRIGHT_SE2_ENUM_SCHEMA_REF,
    _UPRIGHT_SE2_YAW_ARGUMENT_SCHEMA_REF,
    _UPRIGHT_SE2_WORLD_XY_FRAME_REF,
    _UPRIGHT_SE2_METRE_UNIT_REF,
    _UPRIGHT_SE2_CLOSED_INTERVAL_TOPOLOGY_REF,
    _UPRIGHT_SE2_DERIVED_RULE_REF,
    _UPRIGHT_SE2_PRIMARY_ROLES,
    _UPRIGHT_SE2_DERIVED_ROLES,
    _UPRIGHT_SE2_CARDINAL_TURN_FRACTIONS,
    _UPRIGHT_SE2_CARDINAL_QUATERNIONS,
    UPRIGHT_SE2_CARDINAL_OWN_PIVOT_OPERATOR_REF,
    UPRIGHT_SE2_CARDINAL_REFERENCE_PIVOT_OPERATOR_REF,
    UPRIGHT_SE2_CONTINUOUS_OWN_PIVOT_OPERATOR_REF,
    UPRIGHT_SE2_CONTINUOUS_REFERENCE_PIVOT_OPERATOR_REF,
    UPRIGHT_SE2_OPERATOR_REFS,
    UPRIGHT_SE2_PROFILE_CAPABILITY_REF,
    UPRIGHT_SE2_CARDINAL_COMPILER_CAPABILITY_REF,
    UPRIGHT_SE2_CARDINAL_BACKEND_CAPABILITY_REF,
    UPRIGHT_SE2_CARDINAL_CHECKER_CAPABILITY_REF,
    UPRIGHT_SE2_CONTINUOUS_COMPILER_CAPABILITY_REF,
    UPRIGHT_SE2_CONTINUOUS_BACKEND_CAPABILITY_REF,
    UPRIGHT_SE2_CONTINUOUS_CHECKER_CAPABILITY_REF,
    UPRIGHT_SE2_CARDINAL_CAPABILITY_REFS,
    UPRIGHT_SE2_CONTINUOUS_CAPABILITY_REFS,
    UPRIGHT_SE2_STAGED_CAPABILITY_REFS,
    UPRIGHT_SE2_BACKEND_OWNER_REF,
    UPRIGHT_SE2_CHECKER_OWNER_REF,
    UPRIGHT_SE2_COMPILER_OWNER_REF,
    UPRIGHT_SE2_COMPILER_BUILD_SHA256,
    UPRIGHT_SE2_CHECKER_BUILD_SHA256,
    UPRIGHT_SE2_COLLISION_PREDICATE_REF,
    UPRIGHT_SE2_SUPPORT_PREDICATE_REF,
    UPRIGHT_SE2_TARGET_RELATION_PREDICATE_REF,
    UPRIGHT_SE2_PRESERVATION_PREDICATE_REF,
    UPRIGHT_SE2_VISIBILITY_PREDICATE_REF,
    UPRIGHT_SE2_PREDICATE_DEFINITION_REFS,
    UPRIGHT_SE2_OBJECTIVE_DEFINITION_REF,
    UPRIGHT_SE2_PREDICATE_EVALUATOR_CAPABILITY_REF,
    UPRIGHT_SE2_PREDICATE_VERIFIER_CAPABILITY_REF,
    UPRIGHT_SE2_OBJECTIVE_EVALUATOR_CAPABILITY_REF,
    UPRIGHT_SE2_OBJECTIVE_VERIFIER_CAPABILITY_REF,
    UPRIGHT_SE2_PREDICATE_CAPABILITY_REFS,
    UPRIGHT_SE2_OBJECTIVE_CAPABILITY_REFS,
    _ValueT,
    _SEMANTIC_ID_SCHEMA_REF,
    _SEMANTIC_SYMBOL_SCHEMA_REF,
    _SEMANTIC_REAL_SCHEMA_REF,
    _SEMANTIC_TUPLE_SCHEMA_REF,
    UPRIGHT_SE2_SEMANTIC_CLOSURE_DEFINITION_REF,
    _SEMANTIC_DEFINITION_KIND_REF,
    _OBJECTIVE_DEFINITION_KIND_REF,
    _SEMANTIC_CLOSURE_KIND_REF,
    _SEMANTIC_CLOSURE_SCHEMA_REF,
    _OBJECTIVE_POLICY_SCHEMA_REF,
    _EXECUTABLE_POLICY_FAMILY_REF,
    _EXECUTABLE_POLICY_WIRE_SCHEMA_REF,
    _EXECUTABLE_POLICY_BUNDLE_SCHEMA_REF,
    _EXECUTABLE_POLICY_BUNDLE_FACT_KEY,
    _EXECUTABLE_POLICY_KEYS,
    _EXECUTABLE_POLICY_SCHEMA_BY_KEY,
    _SEMANTIC_KIND_TO_REF,
    _SEMANTIC_KIND_TO_SCHEMA,
    _SEMANTIC_BODY_VALUES,
    _UPRIGHT_SE2_RETAINED_POINT_OBJECTIVE_SCHEMA_REF,
    _UPRIGHT_SE2_RETAINED_POINT_TERM_SCHEMA_REF,
    _UPRIGHT_SE2_RETAINED_POINT_TERM_ROSTER_SCHEMA_REF,
    _UPRIGHT_SE2_EXACT_RATIONAL_SCHEMA_REF,
    _M2_Q0_SHARED_VALUE_HASH_DOMAIN,
    _M2_Q0_MAPPING_DEFINITION_ROSTER_HASH_DOMAIN,
    _M2_Q0_SOURCE_PROVENANCE_HASH_DOMAIN,
    _M2_Q0_SUPPORTED_DOMAIN_REF,
    _M2_Q0_DOMAIN_SCHEMA_REF,
    _M2_Q0_DOMAIN_TRANSFORM_REF,
)

from spatialcf.domain._upright_se2.endpoints import (
    _continuous_canonical_yaw_after,
    _continuous_materialized_expected_pose,
    UprightSE2MaterializedEndpoint,
    _materialized_program_arguments,
    _materialized_derived_bundle,
    _materialized_state_real,
    _materialized_pose_value,
    _materialized_derived_fact_value,
    _materialized_derived_fact_roster_value,
    _materialized_expected_after_scene_state,
    _validate_materialized_endpoint_program,
    UprightSE2ProposalCandidate,
    UprightSE2ContinuousMaterializedEndpoint,
    _continuous_materialized_program_arguments,
    _validate_continuous_materialized_endpoint_program,
    UprightSE2ContinuousProposalCandidate,
)

from spatialcf.domain._upright_se2.m2 import (
    _m2_q0_source_leaf_values,
    _m2_q0_source_leaf_selectors,
    _m2_q0_dyadic_from_float,
    _m2_q0_authorized_domain_from_source,
    _m2_q0_domain_typed_value,
    _m2_q0_non_equivalence_values,
    UprightSE2M2Q0MappingDefinition,
    UprightSE2M2Q0MappingRow,
    UprightSE2M2Q0SourceFreeConstructionRow,
    UprightSE2M2Q0Construction,
)

from spatialcf.domain._upright_se2.policies import (
    UprightSE2SemanticOwnerBinding,
    UprightSE2SemanticDefinition,
    UprightSE2ObjectiveTermPolicy,
    UprightSE2FiveTermObjectivePolicy,
    UprightSE2ExecutablePolicyValue,
    UprightSE2ExecutablePolicyBundle,
    _semantic_owner_binding,
    _executable_policy_spec,
    _policy_payload_fields,
    _require_policy_fields,
    _policy_real,
    _policy_integer,
    _policy_symbol,
    _policy_id,
    _policy_digest,
    _policy_tuple,
    _policy_id_tuple,
    _visibility_observation_bound_fields,
    _validate_visibility_observation_bounds,
    _decode_upright_se2_objective_policy_payload,
    _validate_executable_policy_payload,
    _require_policy_values,
    _require_policy_ids,
    _executable_policy_wire,
    executable_policy_bundle_to_typed_value,
    _record_field_map,
    _wire_policy_value,
    request_bound_executable_policy_bundle_from_problem,
    build_upright_se2_executable_policy_bundle,
    decode_upright_se2_objective_policy,
    _validate_executable_policy_resource_binding,
    _objective_term_policy_values,
    _objective_policy_refs,
)

from spatialcf.domain._upright_se2.proof_evaluation import (
    _proof_usage_total,
    UprightSE2RetainedOwnerEvaluation,
    UprightSE2ProofCellEvaluation,
    UprightSE2ProposalPointTerm,
    UprightSE2ProposalPointObjective,
    _retained_point_objective_value,
    _retained_point_owner_objective,
    UprightSE2ProposalPointEvaluation,
    UprightSE2ProofPruneDecision,
    UprightSE2ProofFrontierRow,
    UprightSE2ProofStageDelta,
    UprightSE2ProofResourceLedger,
)

from spatialcf.domain._upright_se2.proof_material import (
    _proof_cell_is_within_root,
    _proof_root_for_cell,
    _proof_validate_leaf_partition,
    _proof_leaf_owns_coordinate,
    UprightSE2ProofMaterial,
    _continuous_proof_cell_within_root,
    _continuous_proof_leaf_owns_coordinate,
    _typed_continuous_bound_proves_inward_feasibility,
    _continuous_point_retains_inward_evidence,
    _continuous_proof_validate_leaf_partition,
    UprightSE2ContinuousProofMaterial,
)

from spatialcf.domain._upright_se2.proof_wire import (
    _proof_wire_record,
    _proof_wire_encode_node,
    _proof_wire_decode_node,
    encode_upright_se2_proof_material,
    decode_upright_se2_proof_material,
    _continuous_proof_wire_record,
    _continuous_proof_wire_encode_node,
    _continuous_proof_wire_decode_node,
    encode_upright_se2_continuous_proof_material,
    decode_upright_se2_continuous_proof_material,
    UprightSE2VerificationBundle,
)

from spatialcf.domain._upright_se2.registration import (
    UprightSE2ProfileRegistration,
)

from spatialcf.domain._upright_se2.semantics import (
    UprightSE2SemanticClosure,
    UprightSE2ContinuousSemanticClosure,
    _upright_semantic_definitions,
    build_upright_se2_q0_target_objective_policy,
    build_upright_se2_objective_expression,
    _semantic_owner_binding_payload,
    _semantic_definition_envelope,
    _objective_term_payload,
    _objective_policy_envelope,
    _semantic_definition_bundle_for_digest,
    _validate_task2_semantic_profile,
    build_upright_se2_semantic_definition_bundle,
    _upright_semantic_owner_bindings,
    build_upright_se2_semantic_closure,
    build_upright_se2_continuous_semantic_closure,
)

from spatialcf.domain._upright_se2.solve_policy import (
    UprightSE2ExactRational,
    UprightSE2SolvePolicyDefinitionPayload,
    _solve_policy_rational_value,
    build_upright_se2_solve_policy_definition_bundle,
    decode_upright_se2_solve_policy_definition_payload,
    UprightSE2CheckerReplayPolicy,
    build_upright_se2_checker_replay_policy,
)

from spatialcf.domain._upright_se2.source_binding import (
    _UprightSE2SourceInput,
    _UprightSE2ContinuousSourceInput,
    validate_upright_se2_executable_policy_visibility_binding,
    _predicate_atom_from_context,
    _validate_grounded_semantic_shape,
    _bound_source_input,
    _bound_continuous_source_input,
    _bound_real,
    _bound_integer,
    _bound_id,
    _bound_symbol,
    _bound_scene_object,
    _bound_predicate_atom,
    _bound_reference,
    _validate_bound_target_atom,
    _validate_bound_preservation_atom,
    _bound_visibility_observation_id,
    _validate_bound_semantic_problem,
    _bound_grounded_obligations,
    _validate_bound_continuous_semantic_problem,
    _bound_continuous_grounded_obligations,
    _DerivedSourceFact,
    _derived_source_identifier,
    _exact_source_values,
)

from spatialcf.domain._upright_se2.state import (
    UprightSE2CompilerClosure,
    UprightSE2TranslationDomain,
    UprightSE2CardinalOperation,
    UprightSE2ContinuousOperation,
    UprightSE2StateFootprint,
    validate_required_upright_support_surface,
    _expected_derived_sources,
    UprightSE2DerivedAfterFact,
    UprightSE2AfterStateTemplate,
    UprightSE2EndpointConstructionRecipe,
    UprightSE2ContinuousEndpointConstructionRecipe,
)

from spatialcf.domain._upright_se2.values import (
    _semantic_definition_ref_for_kind,
    _semantic_definition_schema_for_kind,
    _semantic_capabilities_for_definition,
    _semantic_typed_id,
    _semantic_typed_symbol,
    _semantic_typed_real,
    _semantic_typed_digest,
    _semantic_typed_tuple,
    _semantic_typed_digest_tuple,
    _semantic_typed_record,
    _semantic_definition_body,
    _semantic_operand_schemas,
    _materialized_state_record,
)

from spatialcf.domain._upright_se2.yaw import (
    _require_sorted_unique_by_bytes,
    _is_negative_zero,
    _fraction_from_float,
    CanonicalSO2Angle,
    canonical_yaw_from_upright_quaternion,
    validate_directed_yaw_quaternion_consistency,
    _compose_upright_quaternion_from_primary_yaw,
    CardinalYaw,
    ContinuousYawArc,
    ContinuousYawFullCircle,
    ContinuousYawDomain,
    ExactDyadic,
    LiftedYawInterval,
    ContinuousYawLift,
    PivotMode,
    FixedPivotBinding,
    ExplicitPoseYawBinding,
    CardinalYawAuthorization,
    ContinuousYawAuthorization,
)

__all__ = (
    "UPRIGHT_SE2_CONTINUOUS_PROOF_MATERIAL_DEFINITION_REF",
    "UPRIGHT_SE2_CONTINUOUS_PROOF_MATERIAL_DISCRIMINATOR",
    "UPRIGHT_SE2_CONTINUOUS_PROOF_MATERIAL_PAYLOAD_SCHEMA_REF",
    "UPRIGHT_SE2_DERIVED_SOURCE_HASH_DOMAIN",
    "UPRIGHT_SE2_PROOF_MATERIAL_DEFINITION_REF",
    "UPRIGHT_SE2_PROOF_MATERIAL_DISCRIMINATOR",
    "UPRIGHT_SE2_PROOF_MATERIAL_PAYLOAD_SCHEMA_REF",
    "UPRIGHT_SE2_SEMANTIC_CLOSURE_DEFINITION_REF",
    "UPRIGHT_SE2_YAW_TO_POSE_RULE_REF",
    "CanonicalSO2Angle",
    "CardinalYaw",
    "CardinalYawAuthorization",
    "ContinuousYawArc",
    "ContinuousYawAuthorization",
    "ContinuousYawDomain",
    "ContinuousYawFullCircle",
    "ContinuousYawLift",
    "ExactDyadic",
    "ExplicitPoseYawBinding",
    "FixedPivotBinding",
    "LiftedYawInterval",
    "PivotMode",
    "UprightSE2AfterStateTemplate",
    "UprightSE2BackendAvailability",
    "UprightSE2CardinalOperation",
    "UprightSE2CardinalProofTuple",
    "UprightSE2CheckerReplayPolicy",
    "UprightSE2Compilation",
    "UprightSE2CompiledCell",
    "UprightSE2CompilerClosure",
    "UprightSE2ContinuousCompilation",
    "UprightSE2ContinuousEndpointConstructionRecipe",
    "UprightSE2ContinuousMaterializedEndpoint",
    "UprightSE2ContinuousOperation",
    "UprightSE2ContinuousProofMaterial",
    "UprightSE2ContinuousProofTuple",
    "UprightSE2ContinuousProposalCandidate",
    "UprightSE2ContinuousSemanticClosure",
    "UprightSE2CoverageArtifact",
    "UprightSE2DerivedAfterFact",
    "UprightSE2EndpointConstructionRecipe",
    "UprightSE2ExactRational",
    "UprightSE2ExecutablePolicyBundle",
    "UprightSE2ExecutablePolicyValue",
    "UprightSE2FiveTermObjectivePolicy",
    "UprightSE2M2Q0Construction",
    "UprightSE2M2Q0MappingDefinition",
    "UprightSE2M2Q0MappingRow",
    "UprightSE2M2Q0SourceFreeConstructionRow",
    "UprightSE2MaterializedEndpoint",
    "UprightSE2ObjectiveTermPolicy",
    "UprightSE2ProfileRegistration",
    "UprightSE2ProofCellEvaluation",
    "UprightSE2ProofFrontierRow",
    "UprightSE2ProofLeafDisposition",
    "UprightSE2ProofMaterial",
    "UprightSE2ProofPruneDecision",
    "UprightSE2ProofResourceLedger",
    "UprightSE2ProofStageDelta",
    "UprightSE2ProposalCandidate",
    "UprightSE2ProposalPointEvaluation",
    "UprightSE2ProposalPointObjective",
    "UprightSE2ProposalPointTerm",
    "UprightSE2RetainedOwnerEvaluation",
    "UprightSE2RetainedOwnerOutcomeKind",
    "UprightSE2SemanticClosure",
    "UprightSE2SemanticDefinition",
    "UprightSE2SemanticOwnerBinding",
    "UprightSE2SolvePolicyDefinitionPayload",
    "UprightSE2StateFootprint",
    "UprightSE2TranslationDomain",
    "UprightSE2VerificationBundle",
    "build_upright_se2_checker_replay_policy",
    "build_upright_se2_continuous_semantic_closure",
    "build_upright_se2_executable_policy_bundle",
    "build_upright_se2_objective_expression",
    "build_upright_se2_q0_target_objective_policy",
    "build_upright_se2_semantic_closure",
    "build_upright_se2_semantic_definition_bundle",
    "build_upright_se2_solve_policy_definition_bundle",
    "canonical_yaw_from_upright_quaternion",
    "decode_upright_se2_continuous_proof_material",
    "decode_upright_se2_objective_policy",
    "decode_upright_se2_proof_material",
    "decode_upright_se2_solve_policy_definition_payload",
    "encode_upright_se2_continuous_proof_material",
    "encode_upright_se2_proof_material",
    "request_bound_executable_policy_bundle_from_problem",
    "validate_directed_yaw_quaternion_consistency",
    "validate_required_upright_support_surface",
    "validate_upright_se2_executable_policy_visibility_binding",
)
